mpesa/urls.py
from django.urls import path

from . import views

"""
urlpatterns = [
    path('access/token', views.getAccessToken, name='get_mpesa_access_token'),
    path('online/lipa', views.lipa_na_mpesa_online, name='lipa_na_mpesa'),

     # register, confirmation, validation and callback urls
    path('c2b/register', views.register_urls, name="register_mpesa_validation"),
    path('c2b/confirmation', views.confirmation, name="confirmation"),
    path('c2b/validation', views.validation, name="validation"),
    path('c2b/callback', views.call_back, name="call_back"),
]
"""

wrappers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from saler.views import admin2

urlpatterns = [
    path('admin/home', admin.site.urls),
    path('admin/', admin2, name = 'admin2'),
    path('', include('main.urls')),
    #path('api/v1/', include('mpesa.urls')),
    path('seller/', include('saler.urls')),
    path("login/", auth_views.LoginView.as_view(template_name='main/login.html', redirect_authenticated_user=True), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page='login'), name="logout"),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name='main/password_reset.html'), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'), name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name='main/password_reset_complete.html'), name="password_reset_complete"),
    path("coupon/",include('coupon.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saler/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class SalerDetail(models.Model):
	SEX_CHOICES = (("Male",'Male'),("Female",'Female'),("Other",'Other'))
	STATE_CHOICES = (
		("Mombasa",'Mombasa'),
		("Kwale", "Kwale"),
		("Kilifi", 'Kilfi'),
		("Tana_river", 'Tana rive'),
		("Lamu", 'Lamu'),
		("Taita_taveta", 'Taita taveta'),
		("Garissa", 'Garissa'),
		("Wajir",'Wajir'),
		("Mandera", 'Mandera'),
		("Marsabit", 'Marsabit'),
		("Isiolo", 'Isiolo'),
		("Meru", 'Meru'),
		("Tharaka_nithi", 'Tharaka nithi'),
		("Embu", 'Embu'),
		("Kitui", 'Kitui'),
		("Machaos", 'Machakos'),
		("Makueni", 'Makueni'),
		("Nyandarua", 'Nyandarua'),
		("Nyeri", 'Nyeri'),
		("Kirinyaga", 'Kirinyaga'),
		("Muranga", 'Muranga'),
		("Kiambu", 'Kiambu'),
		("Turkana", 'Turkana'),
		("West_Pokot", 'West Pokot'),
		("Samburu", 'Samburu'),
		("Trans_nzoia", 'Trans Nzoia'),
		("Uasingishu", 'Uasingishu'),
		("Elgeyo_marakwet", 'Elgeyo Marakwet'),
		("Nandi", 'Nandi'),
		("Baringo", 'Baringo'),
		("Laikipia", 'Laikipia'),
		("Nakuru", 'Nakuru'),
		("Narok", 'Narok'),
		("Kajiado", 'Kajiado'),
		("Kericho", 'Kericho'),
		("Bomet", 'Bomet'),
		("Kakamega", 'Kakamega'),
		("Bungoma", 'Bungoma'),
		("Vihiga", 'Vihiga'),
		("Busia", 'Busia'),
		("Siaya", 'Siaya'),
		("Kisumu", 'Kisumu'),
		("Homabay", 'Homabay'),
		("Migori", 'Migori'),
		("Kisii", 'Kisii'),
		("Nyamira", 'Nyamira'),
		("Nairobi", 'Nairobi')
		)
	user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
	photo = models.ImageField(default='default.png',upload_to='user_photos')
	mobile = models.CharField(max_length=10,null=True)
	gst_Number = models.CharField(max_length=15,null=True)
	shop_Name = models.CharField(max_length=500,null=True)
	alternate_mobile = models.CharField(max_length=10,null=True,blank=True)
	shop_Address = models.TextField()
	pincode = models.CharField(max_length=6, null=True)
	landmark = models.CharField(max_length=500, null=True, blank=True)
	locality = models.CharField(max_length=100, null=True, blank=True)
	city = models.CharField(max_length=100, null=True, blank=True)
	state = models.CharField(max_length=50,choices=STATE_CHOICES, null=True)
	account_Holder_Name = models.CharField(max_length=50, null=True)
	account_Number = models.CharField(max_length=20, null=True)
	ifsc_Code = models.CharField(max_length=11, null=True)

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img = Image.open(self.photo.path)
		if img.height > 300 or img.width > 300:
			output_size = (300, 300)
			img.thumbnail(output_size)
			img.save(self.photo.path)

class SellerSlider(models.Model):
	name = models.CharField(max_length=50, default = "", null=True)
	image = models.ImageField(upload_to='seller_slider_img')
	url = models.CharField(max_length=200, default = "#", null=True)

	def __str__(self):
		return f'{self.name}'

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img = Image.open(self.image.path)
		if img.height > 1024 or img.width > 1024:
			output_size = (1024, 1024)
			img.thumbnail(output_size)
			img.save(self.image.path)


class category(models.Model):
	name = models.CharField(max_length=50, default="")
	sub_Categories  = models.TextField(default="")
	def __str__(self):
		return f'{self.name}'

class Product(models.Model):
	GST_CHOICES = (("0",'0'),("3",'3'),("5",'5'),("12",'12'),("18",'18'),("28",'28'))
	product_id = models.BigAutoField(primary_key=True)
	product_id2 = models.CharField(max_length=100,default='')
	shop = models.ForeignKey(User, on_delete=models.CASCADE,default='')
	product_name = models.CharField(max_length=100)
	category = models.ForeignKey(category, default="", verbose_name="Category", on_delete=models.SET_DEFAULT, null=True)
	subcategory = models.CharField(max_length=50, default="")
	price = models.IntegerField(default=0)
	price_not = models.IntegerField(default=999)
	desc = models.TextField()
	gst = models.CharField(default='0',max_length=3,choices=GST_CHOICES)
	pub_date = models.DateField(auto_now=True)
	image1 = models.ImageField(upload_to='products/images', default="",null=True)
	image2 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image3 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image4 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image5 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img1 = Image.open(self.image1.path)
		if img1.height > 1500 or img1.width > 1500:
			output_size = (1500, 1500)
			img1.thumbnail(output_size)
			img1.save(self.image1.path)
		if self.image2:
			img2 = Image.open(self.image2.path)
			if img2.height > 1500 or img2.width > 1500:
				output_size = (1500, 1500)
				img2.thumbnail(output_size)
				img2.save(self.image2.path)

		if self.image3:
			img3 = Image.open(self.image3.path)
			if img3.height > 1500 or img3.width > 1500:
				output_size = (1500, 1500)
				img3.thumbnail(output_size)
				img3.save(self.image3.path)

		if self.image4:
			img4 = Image.open(self.image4.path)
			if img4.height > 1500 or img4.width > 1500:
				output_size = (1500, 1500)
				img4.thumbnail(output_size)
				img4.save(self.image4.path)

		if self.image5:
			img5 = Image.open(self.image5.path)
			if img5.height > 1500 or img5.width > 1500:
				output_size = (1500, 1500)
				img5.thumbnail(output_size)
				img5.save(self.image5.path)
	def __str__(self):
		return f'{self.product_id}'

class ProductSize(models.Model):
	product = models.ForeignKey(Product,on_delete=models.CASCADE)
	size = models.CharField(max_length=20)
	quantity = models.IntegerField(default=0, null=True)

class ProductReview(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	review = models.TextField()
	time = models.DateTimeField(auto_now=True)

class WholeSaleProduct(models.Model):
	SEX_CHOICES = (("Male",'Male'),("Female",'Female'),("All",'All'))
	product_id = models.BigAutoField(primary_key=True)
	product_name = models.CharField(max_length=100)
	category = models.ForeignKey(category, default="", verbose_name="Category", on_delete=models.SET_DEFAULT)
	subcategory = models.CharField(max_length=50, default="")
	price = models.IntegerField(default=0)
	desc = models.TextField()
	size = models.TextField(verbose_name='Size Avialabe(Separated by Comma)')
	color = models.TextField(verbose_name='Enter Color Separated by Comma')
	min_Quantity = models.IntegerField(default=0, null=True)
	pub_date = models.DateField(auto_now=True)
	image1 = models.ImageField(upload_to='products/images', default="",null=True)
	image2 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image3 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image4 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)
	image5 = models.ImageField(upload_to='products/images', default="",null=True,blank=True)

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img1 = Image.open(self.image1.path)
		if img1.height > 1500 or img1.width > 1500:
			output_size = (1500, 1500)
			img1.thumbnail(output_size)
			img1.save(self.image1.path)
		if self.image2:
			img2 = Image.open(self.image2.path)
			if img2.height > 1500 or img2.width > 1500:
				output_size = (1500, 1500)
				img2.thumbnail(output_size)
				img2.save(self.image2.path)

		if self.image3:
			img3 = Image.open(self.image3.path)
			if img3.height > 1500 or img3.width > 1500:
				output_size = (1500, 1500)
				img3.thumbnail(output_size)
				img3.save(self.image3.path)

		if self.image4:
			img4 = Image.open(self.image4.path)
			if img4.height > 1500 or img4.width > 1500:
				output_size = (1500, 1500)
				img4.thumbnail(output_size)
				img4.save(self.image4.path)

		if self.image5:
			img5 = Image.open(self.image5.path)
			if img5.height > 1500 or img5.width > 1500:
				output_size = (1500, 1500)
				img5.thumbnail(output_size)
				img5.save(self.image5.path)
	def __str__(self):
		return f'{self.product_id}'

class WholeSaleProductOrders(models.Model):
	STATUS_CHOICES = (("Accepted",'Accepted'),("Packed",'Packed'),("On The Way",'On The Way'),("Delivered",'Delivered'),("Cancel",'Cancel'))
	order_id = models.CharField(max_length=50,default='')
	user = models.ForeignKey(User, default='', on_delete=models.CASCADE)
	products = models.CharField(max_length=50)
	status = models.CharField(max_length=15,choices=STATUS_CHOICES,default='')

class dow(models.Model):
	product = models.OneToOneField(Product, default="", verbose_name="Product Id", on_delete=models.CASCADE, null=True)
	price = models.PositiveIntegerField()
	def __str__(self):
		return f'{self.product}'

class trend(models.Model):
	product = models.OneToOneField(Product, default="", on_delete=models.CASCADE, null=True)
	number = models.PositiveIntegerField()
	def __str__(self):
		return f'{self.product}'

class MyCart(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	product_id = models.CharField(max_length=100)
	number = models.PositiveIntegerField(default=0)

class Orders(models.Model):
	STATUS_CHOICES = (("Accepted",'Accepted'),("Packed",'Packed'),("On the way",'On the way'),("Delivered",'Delivered'),("Cancel",'Cancel'),("Returned",'Returned'))
	order_id = models.CharField(max_length=50,default='')
	saler = models.CharField(max_length=100,default='wrappers@admin',)
	user = models.ForeignKey(User, default='', on_delete=models.CASCADE)
	products = models.CharField(max_length=50)
	size = models.CharField(max_length=50,default='',null=True)
	number = models.IntegerField(default = 1)
	status = models.CharField(max_length=15,choices=STATUS_CHOICES,default='')

saler/templates/saler/add_product.html
{% extends 'saler/base.html' %}
{% block saler_head %}
{% endblock saler_head %}
{% load crispy_forms_tags %}
{% block saler_body %}
<div class="container">
	{% if messages %}
	{% for message in messages %}
	<div class="alert alert-{{message.tags}}">{{ message }}</div>
	{% endfor %}
	{% endif %}
	<h1 style="text-align: center; letter-spacing: 1px; font-family: Sans-Serif Fonts; font-weight: bolder;">Add Product
	</h1>
	<form method="post" enctype="multipart/form-data">{% csrf_token %}
		<div class="row">
			<div class="col-md">
			  <div class="form-group">
			    <label for="ProductName">Product Name</label>
			    <input type="text" class="form-control" id="ProductName" name="prod_name" placeholder="Enter Product Name" required>
			  </div>
			</div>
			
			<div class="col-md-2">
			    <label for="ProductName">Category</label>
				<select class="custom-select" name="category" id="id_category">
				  <option selected>-----</option>
				  {% for sc in subcat %}
				  <option value="{{sc.0.id}}">{{sc.0}}</option>
				  {% endfor %}
				</select>
			</div>
			<div class="col-md-2">
				<label for="ProductName">SubCategory</label>
				<select class="custom-select" name="subcategory" id="id_subcategory" >
					<option selected>-----</option>
				</select>
			</div>
			<div class="col-md-2">
				<label for="ProductName">Price</label>
				<div class="input-group mb-3">
				  <div class="input-group-prepend">
				    <span class="input-group-text">kshs </span>
				  </div>
				  <input type="number" class="form-control" aria-label="Amount (to the nearest dollar)" name="price" required>
				  
				</div>
			</div>
			<div class="col-md-2">
				<label for="ProductName">Price Not</label>
				<div class="input-group mb-3">
				  <div class="input-group-prepend">
				    <span class="input-group-text">kshs </span>
				  </div>
				  <input type="number" class="form-control" aria-label="Amount (to the nearest dollar)" name="price_not" required>
				  
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-10">
				<div class="input-group">
				  <div class="input-group-prepend">
				    <span class="input-group-text">Description</span>
				  </div>
				  <textarea class="form-control" rows="1" aria-label="With textarea" name="desc"></textarea>
				</div>
			</div>
			<div class="col-md-2">
				<div class="input-group mb-3">
				  <div class="input-group-prepend">
				    <label class="input-group-text" for="inputGroupSelect01">GST</label>
				  </div>
				<select class="custom-select" id="inputGroupSelect01" name="gst" id="inputGroupSelect01">
				  <option value="0" selected>0%</option>
				  <option value="3">3%</option>
				  <option value="5">5%</option>
				  <option value="12">12%</option>
				  <option value="18">18%</option>
				  <option value="28">28%</option>
				</select>
			</div>
		</div>
		</div>
		<label for="ProductName">Images</label>
		<div class="row">
			<div class="col-md">
				<input type="file" name="image1" accept="image/*" class="clearablefileinput form-control" required>
			</div>
			<div class="col-md">
				<input type="file" name="image2" accept="image/*" class="clearablefileinput form-control">
			</div>
			<div class="col-md">
				<input type="file" name="image3" accept="image/*" class="clearablefileinput form-control">
			</div>
			<div class="col-md">
				<input type="file" name="image4" accept="image/*" class="clearablefileinput form-control">
			</div>
			<div class="col-md">
				<input type="file" name="image5" accept="image/*" class="clearablefileinput form-control">
			</div>
		</div>
		<label>Enter Size and Quantity</label>
		<div class="row pb-1" id="sizes">
			<div class="col-sm-2">
				<div class="input-group">
				  <input type="text" aria-label="Size" class="form-control" placeholder="Size" name="size1" >
				  <input type="number" aria-label="Quantity" class="form-control" placeholder="Quantity" name="quantity1" >
				</div>
			</div>
			<input type="number" name="size_no" style="display: none;" id="size_no" value="1">
			<i class="fa fa-plus-circle pt-1" aria-hidden="true" style="font-size: 30px;" onclick="addsizequn()"id='pls'></i>
		</div>
		<button type="submit" class="btn btn-primary"
			style="background-color: #be2714; border: none; width: 100%;">Add</button>
	</form>
</div>
<hr class="mr-5 ml-5 pb-2">
<div class="container">
	<h5 style="text-align: center; font-weight: bold;">Products in Your Store! <a href="{% url 'view_products' %}"
			style="font-size: 15px;"><i class="fa fa-eye" aria-hidden="true"></i>View All</a></h5>
	<div style="max-height: 420px; overflow-y: scroll;">
		<table class="table">
			<thead class="thead-dark">
				<tr>
					<th scope="col">Product Id</th>
					<th scope="col">Product Name</th>
					<th scope="col">category</th>
					<th scope="col">SubCategory</th>
					<th scope="col">price</th>
					<th scope="col" style="text-align: right;"><i class="fa fa-trash" aria-hidden="true"></i></th>
				</tr>
			</thead>
			<tbody>
				{% for pr in prod %}
				<tr>
					<th scope="row">{{pr.product_id}}</th>
					<td>{{pr.product_name}}</td>
					<td>{{pr.category}}</td>
					<td>{{pr.subcategory}}</td>
					<td>{{pr.price}}</td>
					<form>
						<input type="text" name="pro_id" value="{{pr.product_id}}" readonly style="display: none;">
						<td style="text-align: right;"><button type="submit" class="btn" style="margin: 0;padding: 0"><i
									class="fa fa-trash" aria-hidden="true"></i></button></td>

					</form>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
<script>
	var sq = 1;
	function addsizequn(){
		let elm = document.createElement('div');
		document.getElementById('pls').remove();
		sq++;
		elm.className = 'col-sm-2';
		elm.innerHTML = `<div class="input-group">
					  <input type="text" aria-label="Size" class="form-control" placeholder="Size" name="size${sq}">
					  <input type="number" aria-label="Quantity" class="form-control" placeholder="Quantity" name="quantity${sq}">
					</div>
					<i class="fa fa-plus-circle pt-1" aria-hidden="true" style="font-size: 30px;" onclick="addsizequn()" id='pls'></i>`;
		sub = document.getElementById('sizes');
		sub.appendChild(elm);
		document.getElementById('size_no').value = sq;
	}
</script>
<script type="text/javascript">
	function subcat() {
		{% for sc in subcat %}
		if (document.getElementById('id_category').value == {{sc.0.id}}) {
		$("#id_subcategory")
	    .replaceWith('<select id="id_subcategory" name="subcategory" class="select form-control">' +
	    	 {% for op in sc|slice:"1:" %}
	          '<option value="{{op}}">{{op}}</option>' +
	         {% endfor %}
	        '</select>');
		}
	    {% endfor %}
	}
	subcat();
	document.getElementById('id_category').onchange = subcat;
</script>
{% endblock saler_body %}

saler/templates/saler/checkout.html
{% extends 'saler/base.html' %}
{% load static %}
{% block saler_head %}
{% load crispy_forms_tags %}
<title>{{request.user.first_name}} Cart</title>
<style type="text/css">
    h3 {
        color: #000;
        font-size: 26px;
        font-weight: 300;
        text-align: center;
        text-transform: uppercase;
        position: relative;
    }

    h3 b {
        color: #be2714;
    }

    h3::after {
        content: "";
        width: 100px;
        position: absolute;
        margin: 0 auto;
        height: 4px;
        border-radius: 1px;
        background: #be2714;
        left: 0;
        right: 0;
        bottom: -5px;
    }
</style>
{% endblock saler_head %}
{% block saler_body %}
<div class="container">
    <h3><b>Checkout</b></h3>
    <div class="col my-4">
        <div class="my-4">
            <ul class="list-group">
                {% for cprod, prod in allProds %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div><img src="{{prod.image1.url}}" style="height: 25px; width: 25px;"
                            class="image-responsive mr-3">{{prod.product_name}}</div>
                    <span class="badge badge-primary badge-pill">{{cprod.number}}</span>
                </li>
                {% endfor %}
            </ul>
        </div>
        <b style="float: right;">Total Payable Ksh {{total}} </b>.
    </div>
    <hr>
    <div class="col my-4">
        <h4 style="text-align: center;">Enter Address & Other Details:</h4>
        <form method="post" action="#">{% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{address_form.shop_Name|as_crispy_field}}
                </div>
                <div class="form-group col-md-3">
                    {{address_form.mobile|as_crispy_field}}
                </div>
                <div class="form-group col-md-3">
                    {{address_form.alternate_mobile|as_crispy_field}}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-9">
                    {{address_form.shop_Address|as_crispy_field}}
                </div>
                <div class="form-group col-md-3">
                    {{address_form.landmark|as_crispy_field}}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    {{address_form.locality|as_crispy_field}}
                </div>
                <div class="form-group col-md-3">
                    {{address_form.city|as_crispy_field}}
                </div>
                <div class="form-group col-md-3">
                    {{address_form.state|as_crispy_field}}
                </div>
                <div class="form-group col-md-3">
                    {{address_form.pincode|as_crispy_field}}
                </div>
            </div>
            <button type="submit" class="btn btn-danger">Payment</button>
        </form>
    </div>
</div>

{% endblock saler_body %}

saler/templates/saler/productview.html
{% extends 'saler/base.html' %}
{% load static %}
{% block saler_head %}
<link rel="stylesheet" type="text/css" href="{% static 'saler/css/productview.css' %}">
<link href='https://fonts.googleapis.com/css?family=Ubuntu+Mono' rel='stylesheet' type='text/css'>
{% endblock saler_head %}
{% block saler_body %}
<div class="container-fluid">
    <div class="card">
        <div class="row">
            <div class="col-md-5">
                <img src="{{product.image1.url}}" class="image-responsive">
            </div>
            <div class="col-md-7">
                   <h1>{{product.produce_name}}</h1>
                    <p class="description">
                   {{product.desc}}
                  </p>
                  
                    
                    <div class="row">
                     <div class="col-md-12 bottom-rule">
                      <h2 class="product-price">kshs  {{product.price}}</h2>
                     </div>
                    </div><!-- end row -->

            </div>
        </div>
    </div>
</div>
{% endblock saler_body %}

saler/templates/saler/seller_signup.html
{% extends 'main/account_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_account %}
<style type="text/css">
  input {
    display: none;
  }
</style>
<form method="POST" class="signup_form mr-2 ml-2">
  {% csrf_token %}
  <fieldset>
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.first_name | as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.last_name | as_crispy_field }}
      </div>
    </div>
    {{ form.username| as_crispy_field }}
    <p id="error_1_id_username" class="invalid-feedback" style="display: inline-block;"><strong id="usrerr"></strong>
    </p>
    {{ form.shop| as_crispy_field }}
    {{ form.gst| as_crispy_field }}
    <p id="error_1_id_username" class="invalid-feedback" style="display: inline-block;"><strong id="gstt"></strong>
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{form.password1 | as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.password2 | as_crispy_field }}
      </div>
    </div>
  </fieldset>
  <section class="mt-4 mr-1 ml-1">
    <button type="submit" id="disbtn1">Sign Up</button>
    <small>Already Registered? &nbsp;<a href="{% url 'login' %}">Log In</a></small>
  </section>
  <div class="subtitle pt-2 mt-1"></div>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
  function ValidateEmail(mail) {
    var mailformat = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    if (mail.match(mailformat)) {
      document.getElementById('usrerr').innerText = "";
      document.getElementById('disbtn1').disabled = false;

      return (true)
    }
    document.getElementById('usrerr').innerText = "You have entered an invalid email address!";
    document.getElementById('disbtn1').disabled = true;

    return (false)
  }

  function validate() {
    var data = document.getElementById("id_username").value;
    checkNumberorEmail();

  }
  function phonenumber(inputtxt) {
    var phoneno = /^\d{10}$/;
    if (inputtxt.match(phoneno)) {
      document.getElementById('usrerr').innerText = "";
      document.getElementById('disbtn1').disabled = false;
      return true;
    }
    else {
      document.getElementById('usrerr').innerText = "enter 10 digit number";
      document.getElementById('disbtn1').disabled = true;

      return false;
    }
  }


  function checkNumberorEmail() {
    var data = document.getElementById("id_username").value;
    if (isNaN(data)) {
      ValidateEmail(data);

    }
    else {
      phonenumber(data);
    }
  }
</script>
<script>
      $(document).on('change',"#id_gst", function(){
        var inputvalues = $(this).val();
        var gstinformat = new RegExp('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$');

        if (gstinformat.test(inputvalues)) {
         return true;
        } else {
            document.getElementById('gstt').innerText = 'Please Enter Valid GSTIN Number';
            $("#id_gst").val('');
            $("#id_gst").focus();
        }

    });
    </script>
{% endblock body_account %}